SET SERVEROUTPUT ON;
ACCEPT A NUMBER PROMPT 'ENTER SIDE OF SQUARE: '
ACCEPT R NUMBER PROMPT 'ENTER RADIUS OF CIRCLE: '

DECLARE
    A     NUMBER := &A;
    R     NUMBER := &R;
    AREAS NUMBER;
    AREAC NUMBER;
    PI    CONSTANT NUMBER := 3.14;
BEGIN
    AREAS := A * A;
    AREAC := PI * R * R;
    DBMS_OUTPUT.PUT_LINE('AREA OF SQUARE = ' || AREAS);
    DBMS_OUTPUT.PUT_LINE('AREA OF CIRCLE = ' || AREAC);
END;