CREATE DATABASE IF NOT EXISTS CUSTOMER_DB;
USE CUSTOMER_DB;

CREATE TABLE CUSTOMER (
    CUS_ID INT PRIMARY KEY,
    CUS_NAME VARCHAR(20) NOT NULL,
    BRANCH VARCHAR(20) NOT NULL,
    AC_NO NUMERIC(5, 0) NOT NULL,
    BALANCE NUMERIC(8, 2) NOT NULL CHECK (BALANCE > 500)
);

INSERT INTO CUSTOMER VALUES (1, "AJAS", "PAISAKARY", 20202, 1000.00),
(2, "ADI", "IRIITY", 49948, 49999.00),
(3, "SONU", "IDUKI", 49388, 3993.00);

SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER
WHERE BALANCE BETWEEN 2000 AND 30000;

SELECT DISTINCT BRANCH FROM CUSTOMER;

SELECT * FROM CUSTOMER
WHERE BRANCH = "IRIITY" AND BALANCE > 500;

SELECT * FROM CUSTOMER
WHERE CUS_NAME LIKE "A%";

SELECT BRANCH AS CITY FROM CUSTOMER;

SELECT SUM(BALANCE) FROM CUSTOMER;

SELECT AVG(BALANCE) FROM CUSTOMER;

SELECT MAX(BALANCE) FROM CUSTOMER;

SELECT MIN(BALANCE) FROM CUSTOMER;

SELECT COUNT(*) FROM CUSTOMER;

ALTER TABLE CUSTOMER MODIFY CUS_NAME VARCHAR(50);

ALTER TABLE CUSTOMER ADD ADDRESS VARCHAR(10);

UPDATE CUSTOMER SET ADDRESS = "OLD TOWN"
WHERE CUS_NAME = "AJAS";
UPDATE CUSTOMER SET ADDRESS = "NEW TOWN"
WHERE CUS_NAME = "ADI";
UPDATE CUSTOMER SET ADDRESS = "NEAR RIVER"
WHERE CUS_NAME = "SONU";

SELECT * FROM CUSTOMER;
