CREATE DATABASE IF NOT EXISTS EMPLOYEE_DB;
USE EMPLOYEE_DB;

CREATE TABLE EMPLOYEE (
    EMPNO INT PRIMARY KEY,
    EMPNAME VARCHAR(10),
    PLACE VARCHAR(10),
    DESIG VARCHAR(10),
    SALARY INT DEFAULT 10000,
    DEPT_NO INT CHECK (DEPT_NO BETWEEN 0 AND 10),
    DEPT_NAME VARCHAR(10)
);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, PLACE, DESIG, SALARY, DEPT_NO, DEPT_NAME)
VALUES
(101, 'ARUN', 'KOCHI', 'ENGINEER', 25000, 2, 'IT'),
(102, 'MEERA', 'DELHI', 'MANAGER', 40000, 5, 'HR'),
(103, 'RAHUL', 'MUMBAI', 'CLERK', DEFAULT, 3, 'ADMIN'),
(104, 'PRIYA', 'CHENNAI', 'ANALYST', 32000, 7, 'FINANCE'),
(105, 'NEHA', 'BANGALORE', 'DEVELOPER', 28000, 2, 'IT');

SELECT
    EMPNO,
    EMPNAME,
    SALARY
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE SALARY > 10000;

UPDATE EMPLOYEE
SET SALARY = SALARY + 10000
WHERE DESIG = 'OFFICER';

SELECT * FROM EMPLOYEE;

SELECT
    EMPNO,
    EMPNAME
FROM EMPLOYEE
WHERE SALARY > 10000 AND SALARY < 15000;

SELECT * FROM EMPLOYEE
WHERE EMPNAME LIKE 'A%';

UPDATE EMPLOYEE
SET SALARY = 15000
WHERE DESIG = 'OFFICER';

SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
ADD DISTRICT VARCHAR(20);

SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
DROP COLUMN DISTRICT;

SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE RENAME COLUMN DESIG TO DESIGNATION;

SELECT * FROM EMPLOYEE;
