SET SERVEROUTPUT ON;
ACCEPT S NUMBER PROMPT 'ENTER SALARY: '

DECLARE
    S NUMBER(10) := &S;
BEGIN
    IF S > 30000 THEN
        S := S + S * 0.20;
    ELSIF S > 25000 THEN
        S := S + S * 0.25;
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO CHANGE IN SALARY');
    END IF;

    DBMS_OUTPUT.PUT_LINE('NEW SALARY = ' || S);
END;