CREATE TABLE STUDSEQ (
    ROLLNO NUMBER(6),
    NAME   CHAR(10),
    MARK   NUMBER(3)
);

CREATE SEQUENCE SEQ1 INCREMENT BY 1 START WITH 101 MAXVALUE 200 MINVALUE 101 CYCLE;

SELECT
    SEQ1.NEXTVAL
FROM
    DUAL;

SELECT
    SEQ1.CURRVAL
FROM
    DUAL;

ALTER SEQUENCE SEQ1 INCREMENT BY 2;

SELECT
    SEQ1.NEXTVAL
FROM
    DUAL;

INSERT INTO STUDSEQ VALUES ( SEQ1.NEXTVAL,
                             'RESHMA',
                             76 );

SELECT
    *
FROM
    STUDSEQ;