SET SERVEROUTPUT ON;
ACCEPT S1 CHAR PROMPT 'ENTER A STRING TO REVERSE: '

DECLARE
    S1 VARCHAR2(100) := '&S1';
    S2 VARCHAR2(100) := '';
    A  NUMBER;
BEGIN
    A := LENGTH(S1);
    FOR I IN REVERSE 1..A LOOP
        S2 := S2
              || SUBSTR(S1, I, 1);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('REVERSED STRING: ' || S2);
END;