CREATE DATABASE IF NOT EXISTS STUDENT_DB;

USE STUDENT_DB;

CREATE TABLE STUDENT (
    ROLLNO INT PRIMARY KEY,
    NAME CHAR(20) NOT NULL
    CHECK (NAME LIKE 'B%' OR NAME LIKE 'S%' OR NAME LIKE 'E%' OR NAME LIKE 'P%'),
    SEX CHAR(1) CHECK (SEX = 'M' OR SEX = 'F'),
    DOB DATE NOT NULL,
    COURSE VARCHAR(20) CHECK (COURSE = 'MCA' OR COURSE = 'CSE' OR COURSE = 'ME'),
    SEM VARCHAR(20) CHECK (SEM = 'S3' OR SEM = 'S4'),
    DATE_OF_JOIN DATE
);

INSERT INTO STUDENT (ROLLNO, NAME, SEX, DOB, COURSE, SEM, DATE_OF_JOIN) VALUES
(1, 'Balu', 'M', '2002-05-12', 'CSE', 'S3', '2023-06-01'),
(2, 'Sneha', 'F', '2001-11-25', 'MCA', 'S4', '2023-06-05'),
(3, 'Espan', 'M', '2002-03-17', 'ME', 'S3', '2023-06-10'),
(4, 'Priya', 'F', '2003-01-20', 'CSE', 'S4', '2023-06-15'),
(5, 'Suresh', 'M', '2002-07-30', 'MCA', 'S3', '2023-06-20');

SELECT * FROM STUDENT;

CREATE TABLE MARKS (
    MID INT PRIMARY KEY,
    ROLLNO INT NOT NULL,
    SUB_CODE CHAR(5) NOT NULL,
    MARK INT CHECK (MARK BETWEEN 0 AND 100),
    CONSTRAINT FK FOREIGN KEY (ROLLNO) REFERENCES STUDENT (ROLLNO)
);

INSERT INTO MARKS (MID, ROLLNO, SUB_CODE, MARK) VALUES
(1, 1, 'CSE01', 85),
(2, 2, 'MCA02', 92),
(3, 3, 'ME01', 78),
(4, 4, 'CSE02', 88),
(5, 5, 'MCA01', 95);

SELECT * FROM MARKS;

SELECT NAME FROM STUDENT
WHERE DATE_OF_JOIN > '2023-06-20' AND COURSE = 'MCA';


SELECT NAME FROM STUDENT
WHERE COURSE <> 'CSE';

SELECT NAME FROM STUDENT
WHERE NAME LIKE 'E_p%';

SELECT M.MARK FROM STUDENT AS S, MARKS AS M
WHERE
    S.ROLLNO = M.ROLLNO
    AND S.NAME = 'Sneha' AND S.COURSE = 'MCA';

SELECT DISTINCT STUDENT.ROLLNO FROM STUDENT, MARKS;

SELECT STUDENT.ROLLNO FROM STUDENT, MARKS
WHERE STUDENT.ROLLNO = MARKS.ROLLNO;

SELECT
    STUDENT.NAME,
    MARKS.MARK
FROM STUDENT, MARKS
WHERE STUDENT.ROLLNO = MARKS.ROLLNO AND MARKS.ROLLNO = 2;

SELECT
    ROLLNO,
    MARK AS TOTAL_MARKS
FROM MARKS;

SELECT
    STUDENT.NAME,
    MARKS.ROLLNO
FROM STUDENT, MARKS
WHERE STUDENT.ROLLNO = MARKS.ROLLNO;

SELECT
    NAME,
    S.ROLLNO,
    SEX,
    DOB,
    SUB_CODE,
    MARK
FROM STUDENT AS S, MARKS AS M
WHERE S.ROLLNO = M.ROLLNO AND MARK = (SELECT MAX(MARK) FROM MARKS);

SELECT TO_CHAR(DATE_OF_JOIN, 'DD-MM-YYYY') AS DATE_OF_JOIN FROM STUDENT;

SELECT * FROM STUDENT
WHERE TO_CHAR(DATE_OF_JOIN, 'YYYY') = '2023';

SELECT
    SUB_CODE,
    MIN(MARK)
FROM MARKS
WHERE MARK > 60
GROUP BY SUB_CODE;

SELECT * FROM STUDENT
WHERE COURSE <> 'CSE';

SELECT
    SUB_CODE,
    COUNT(*)
FROM MARKS, STUDENT
WHERE MARK > 60
GROUP BY SUB_CODE;
