CREATE DATABASE VIEW_CREATION;

USE VIEW_CREATION;

CREATE TABLE STUDENT(R_NO INT(3) PRIMARY KEY, NAME CHAR(10), AGE INT(3), PLACE CHAR(10));

INSERT INTO STUDENT  VALUES (1, "NORAH", 17, "SHARJAH"), (2, "ALEX", 18, "DUBAI"), (3, "EMILY", 17, "DUBAI"
);

SELECT * FROM STUDENT;

CREATE VIEW STUDENT1 AS SELECT R_NO, NAME FROM STUDENT ;

SELECT * FROM STUDENT1;

DESC STUDENT1;

INSERT INTO STUDENT1 VALUES (4, "BRIDGET");

SELECT * FROM STUDENT1;

UPDATE STUDENT1 SET NAME = "SERENA" WHERE R_NO = 4;

SELECT * FROM STUDENT1;

DELETE FROM STUDENT1 WHERE R_NO = 1;

SELECT * FROM STUDENT1;

CREATE VIEW STUDENT2 AS SELECT NAME, AGE  FROM STUDENT;

SELECT * FROM STUDENT2;

INSERT INTO STUDENT2 VALUES ("ANU", 22);
