name: DBMS-Lab CI

on:
  push:
    branches: [ main ]

jobs:
  
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Lint SQL files
        run: sqlfluff lint src/employee_database.sql src/customer_database.sql src/student_db.sql src/data_modular_db.sql src/view_crea             tion.sql --dialect mysql
